[project]
name = "foldkit"
version = "1.0.2"
description = "Toolkit for working with and storing AlphaFold3 co-folding results"
authors = [{name="Jonathan Levine", email="jonalevine1@gmail.com"}]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
keywords = ["protein", "protein design", "alphafold", "bioinformatics"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

dependencies = [
    "numpy",
    "pandas",
    "biopython",
    "tqdm",
    "argcomplete"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

docs = [
    "sphinx",
    "pydata-sphinx-theme",
    "sphinx-copybutton",
    "sphinx-autodoc-typehints",
    "sphinx-design"
]

[project.urls]
Documentation = "https://jonlevi.github.io/foldkit/"
Source = "https://github.com/jonlevi/foldkit"
 

[project.scripts]
foldkit = "foldkit.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
